#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
#
version: 1.0.0

#
# The client section used by GO SDK.
#
client:

  organization: Org1
  cryptoconfig:
    path: /root/ki-sdkcrypto-config/
  credentialStore:
    # [Optional]. Used by user store. Not needed if all credentials are embedded in configuration
    # and enrollments are performed elswhere.
    path: "/tmp/state-store"

    # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations
    # requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
      path: /tmp/msp

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     level: 256

  tlsCerts:
    # [Optional]. Use system certificate pool when connecting to peers, orderers (for negotiating TLS) Default: false
    systemCertPool: true

    # [Optional]. Client key and cert for TLS handshake with peers and orderers
    client:
      key:
        path: /root/ki-sdkcrypto-config/peerOrganizations/org1.bookstore.com/users/Admin@org1.bookstore.com/tls/client.key
      cert:
        path: /root/ki-sdkcrypto-config/peerOrganizations/org1.bookstore.com/users/Admin@org1.bookstore.com/tls/client.crt

channels:

  bookchannel:

    peers:
      peer0.org1.bookstore.com:
        endorsingPeer: true

        chaincodeQuery: true

        ledgerQuery: true

        eventSource: true
      peer1.org1.bookstore.com:

        endorsingPeer: true


        chaincodeQuery: true


        ledgerQuery: true


        eventSource: true
      peer0.org2.bookstore.com:

        endorsingPeer: true


        chaincodeQuery: true


        ledgerQuery: true


        eventSource: true
      peer1.org2.bookstore.com:

        endorsingPeer: true


        chaincodeQuery: true

        ledgerQuery: true


        eventSource: true


    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 8
        peerMonitorPeriod: 6s

organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: /root/ki-sdkcrypto-config/peerOrganizations/org1.bookstore.com/users/{username}@org1.bookstore.com/msp
    peers:
      - peer0.org1.bookstore.com
      - peer1.org1.bookstore.com

  Org2:
    mspid: Org2MSP

    # This org's MSP store (absolute path or relative to client.cryptoconfig)
    cryptoPath: /root/ki-sdkcrypto-config/peerOrganizations/org2.bookstore.com/users/{username}@org2.bookstore.com/msp

    peers:
      - peer0.org2.bookstore.com
      - peer1.org2.bookstore.com


  # Orderer Org name
  ordererorg:
      # Membership Service Provider ID for this organization
      mspID: OrdererMSP

      # Needed to load users crypto keys and certs for this org (absolute path or relative to global crypto path, DEV mode)
      cryptoPath:  /root/ki-sdkcrypto-config/ordererOrganizations/bookstore.com/users/{username}@bookstore.com/msp

orderers:
  orderer1.bookstore.com:
    # [Optional] Default: Infer from hostname
    url: orderer1.bookstore.com:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer1.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path D:\Git\ki-sdk\crypto-config
      path: /root/ki-sdkcrypto-config/ordererOrganizations/bookstore.com/tlsca/tlsca.bookstore.com-cert.pem
  orderer2.bookstore.com:
    # [Optional] Default: Infer from hostname
    url: orderer2.bookstore.com:8050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer2.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path D:\Git\ki-sdk\crypto-config
      path: /root/ki-sdkcrypto-config/ordererOrganizations/bookstore.com/tlsca/tlsca.bookstore.com-cert.pem
  orderer3.bookstore.com:
    # [Optional] Default: Infer from hostname
    url: orderer3.bookstore.com:9050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer3.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path D:\Git\ki-sdk\crypto-config
      path: /root/ki-sdkcrypto-config/ordererOrganizations/bookstore.com/tlsca/tlsca.bookstore.com-cert.pem
  orderer4.bookstore.com:
    # [Optional] Default: Infer from hostname
    url: orderer4.bookstore.com:10050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer4.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path D:\Git\ki-sdk\crypto-config
      path: /root/ki-sdkcrypto-config/ordererOrganizations/bookstore.com/tlsca/tlsca.bookstore.com-cert.pem
  orderer5.bookstore.com:
    # [Optional] Default: Infer from hostname
    url: orderer5.bookstore.com:11050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer5.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path D:\Git\ki-sdk\crypto-config
      path: /root/ki-sdkcrypto-config/ordererOrganizations/bookstore.com/tlsca/tlsca.bookstore.com-cert.pem

peers:
  peer0.org1.bookstore.com:
    # this URL is used to send endorsement and query requests
    # [Optional] Default: Infer from hostname
    url: peer0.org1.bookstore.com:7051

    grpcOptions:
      ssl-target-name-override: peer0.org1.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path
      path: /root/ki-sdkcrypto-config/peerOrganizations/org1.bookstore.com/tlsca/tlsca.org1.bookstore.com-cert.pem

  peer1.org1.bookstore.com:
    # this URL is used to send endorsement and query requests
    url: peer1.org1.bookstore.com:8051

    grpcOptions:
      ssl-target-name-override: peer1.org1.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path
      path: /root/ki-sdkcrypto-config/peerOrganizations/org1.bookstore.com/tlsca/tlsca.org1.bookstore.com-cert.pem

  peer0.org2.bookstore.com:
    url: peer0.org2.bookstore.com:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      path: /root/ki-sdkcrypto-config/peerOrganizations/org2.bookstore.com/tlsca/tlsca.org2.bookstore.com-cert.pem
  
  peer1.org2.bookstore.com:
    url: peer0.org2.bookstore.com:10051
    grpcOptions:
      ssl-target-name-override: peer0.org2.bookstore.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      path: /root/ki-sdkcrypto-config/peerOrganizations/org2.bookstore.com/tlsca/tlsca.org2.bookstore.com-cert.pem

entityMatchers:
 peer:
   - pattern: peer0.org1.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:7051
     sslTargetOverrideUrlSubstitutionExp: peer0.org1.bookstore.com
     mappedHost: peer0.org1.bookstore.com

   - pattern: peer1.org1.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:8051
     sslTargetOverrideUrlSubstitutionExp: peer1.org1.bookstore.com
     mappedHost: peer1.org1.bookstore.com

   - pattern: peer0.org2.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:9051
     sslTargetOverrideUrlSubstitutionExp: peer0.org2.bookstore.com
     mappedHost: peer0.org2.bookstore.com

   - pattern: peer1.org2.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:10051
     sslTargetOverrideUrlSubstitutionExp: peer1.org2.bookstore.com
     mappedHost: peer1.org2.bookstore.com

 orderer:
   - pattern: orderer1.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:7050
     sslTargetOverrideUrlSubstitutionExp: orderer1.bookstore.com
     mappedHost: orderer1.bookstore.com

   - pattern: orderer2.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:8050
     sslTargetOverrideUrlSubstitutionExp: orderer2.bookstore.com
     mappedHost: orderer2.bookstore.com

   - pattern: orderer3.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:9050
     sslTargetOverrideUrlSubstitutionExp: orderer3.bookstore.com
     mappedHost: orderer3.bookstore.com

   - pattern: orderer4.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:10050
     sslTargetOverrideUrlSubstitutionExp: orderer4.bookstore.com
     mappedHost: orderer4.bookstore.com

   - pattern: orderer5.bookstore.com
     urlSubstitutionExp: grpcs://127.0.0.1:11050
     sslTargetOverrideUrlSubstitutionExp: orderer5.bookstore.com
     mappedHost: orderer5.bookstore.com