package controller

import (
	"log"

	g "github.com/gin-gonic/gin"
)

func setDb(c *g.Context) {

	// 序列化 数据
	data, err := serializeBydb(c)

	//

	log.Println("db=============>", data)
	log.Println("err===>", err)

}

func serializeBydb(c *g.Context) (p *AutoGenerated, err error) {

	if err := c.ShouldBindJSON(&p); err != nil {
		return p, err
	}
	return p, nil
}
